# Generated by Django 3.2.6 on 2021-08-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210826_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
