# Generated by Django 3.2.6 on 2021-08-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_product_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=150)),
                ('onstock', models.IntegerField()),
                ('season', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='Pictures')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
